version: '3.8'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: jvestoque_sqlserver
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${SA_PASSWORD}
        ports:
            - "1433:1433"
        volumes:
            - sqlserver_data:/var/opt/mssql
        restart: unless-stopped

volumes:
    sqlserver_data: